config/routes.rb
Cantucci::Application.routes.draw do
    
  get "fotos/index"

  resources :enquetes

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  delete '/admin/mensagem_usuarios/:id(.:format)', :action => 'destroy', :controller => 'admin/mensagem_usuarios', :as => :destroy_admin_mensagem_usuario
  
  match '/vinhos/' => 'vinhos#index', :as => :vinhos
  
  get '/contato' => 'mensagem_usuarios#new', :as => :contato

  post '/contato' => 'mensagem_usuarios#create', :as  => :mensagem_usuarios
    
  match '/cardapio/' => 'cardapio_elementos#index', :as => :cardapio
  
  match '/resultado_enquete/' => 'enquetes#resultado', :as => :resultado

  match '/enquete/' => 'enquetes#iago', :as => :enquete
  
  match '/agenda/' => 'eventos#index', :as => :agenda
  
  put '/resultado_enquete/' => "enquetes#update", :as => :update
  
  root :to => "enquetes#home"
  
  match 'frontend/:template' => 'frontend#show', as: :frontend
  
  match '/fotos/' => 'fotos#index', :as => :fotos
  
  match '/cardapio_semanal/' => "cardapio_semanal_elementos#index", :as => :cardapio_semanal
  
  match '/encomendas/' => "encomendas#index"
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cardapio_categoria.rb
class CardapioCategoria < ActiveRecord::Base
  has_many :cardapio_elementos
  mount_uploader :foto, FotoUploader
  
  validates_presence_of :title
  validates_uniqueness_of :title
end

app/models/cardapio_elemento.rb
class CardapioElemento < ActiveRecord::Base
  belongs_to :cardapio_categoria
  
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :cardapio_categoria
end

app/models/cardapio_semanal_elemento.rb
class CardapioSemanalElemento < ActiveRecord::Base
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :week_day
  
  def self.find_by_day(day)
    CardapioSemanalElemento.order("priority ASC").where(:week_day => day)
  end
end

app/models/encomenda_elemento.rb
class EncomendaElemento < ActiveRecord::Base
  mount_uploader :photo, FotoUploader
end

app/models/enquete.rb
class Enquete < ActiveRecord::Base
end

app/models/evento.rb
class Evento < ActiveRecord::Base
 mount_uploader :foto, FotoUploader
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  mount_uploader :picture, FotoUploader
end

app/models/mensagem_usuario.rb
class MensagemUsuario < ActiveRecord::Base
  attr_accessible :name, :email, :phone, :subject, :message
  
  validates_presence_of :name, :email, :phone, :subject, :message
end

app/models/vinho.rb
class Vinho < ActiveRecord::Base
  belongs_to :vinho_categoria
  
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :vinho_categoria
end

app/models/vinho_categoria.rb
class VinhoCategoria < ActiveRecord::Base
  has_many :vinhos, :dependent => :destroy
  
  validates_presence_of :title
  validates_uniqueness_of :title
end

app/controllers/encomendas_controller.rb
class EncomendasController < ApplicationController
  def index
    @carrinho = []
    case params[:resposta]
      when nil
        session[:carrinho] = nil
        session[:carrinho] = []
      
      when "Encomendar!"
        if !session[:carrinho].include?(params[:encomenda])
          session[:carrinho] << params[:encomenda]
        end
        
      when "Remover!"
        session[:carrinho].delete_if {|x| x == params[:encomenda]}
    end
    
    @precoTotal = 0.0
    session[:carrinho].each do |en|
      @carrinho << EncomendaElemento.find(en)
      @precoTotal += EncomendaElemento.find(en).price.to_f
    end
    
    @encomendas = EncomendaElemento.all
    
  end
end

app/controllers/enquetes_controller.rb
class EnquetesController < ApplicationController
  def home
    @enquete = Enquete.limit(1).order("created_at DESC")
  end
  
  def resultado
    @option = params[:opcao_usuario]
    @enquete = Enquete.limit(1).order("created_at DESC")
   
    @enquete.each do |enq|
      if(@option == enq.op1)
        enq.update_attributes(:cop1 => enq.cop1.next)
      elsif(@option == enq.op2)
        enq.update_attributes(:cop2 => enq.cop2.next)
      else
        enq.update_attributes(:cop3 => enq.cop3.next)
      end
      
      @porc1 =  Float(100*enq.cop1)/Float(enq.cop1+enq.cop2+enq.cop3)
      @porc2 =  Float(100*enq.cop2)/Float(enq.cop1+enq.cop2+enq.cop3)
      @porc3 =  Float(100*enq.cop3)/Float(enq.cop1+enq.cop2+enq.cop3)
      
  
    end
  end
  
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  
  def index
    @eventos = Evento.limit(7).order("data_e_hora DESC")
  end
  
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  def index
    @fotos = Foto.all
  end

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def show
    render params[:template]
  end
end

app/controllers/vinhos_controller.rb
class VinhosController < ApplicationController
  
  def index 
      @categorias = VinhoCategoria.all
      @vinhos = Vinho.all
  end
  
end

app/helpers/encomendas_helper.rb
module EncomendasHelper
end

app/helpers/enquetes_helper.rb
module EnquetesHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/mensagem_usuarios_helper.rb
module MensagemUsuariosHelper
end

app/helpers/vinhos_helper.rb
module VinhosHelper
end

app/views/enquetes/home.html.slim
.ladrilhoPrincipalHome
  img#fotoHome src="/images/foto-home.jpg"

  #divindex
    #cont 
      #QuemSomos
        h2 Quem Somos
        p.paragrafo Fundado em 2.011 e com decoração renomada o Cantucci Caffè é um espaço localizado na área central de Brasília que impressiona já na chegada.
          
        p Em um ambiente aconchegante que faz lembrar a Toscana , aqui você encontra bom atendimento, música ambiente, wi-fi e um dos melhores cafés de Brasília.
          
        p No almoço, um cardápio executivo facilita seu dia-a-dia e a noite... brilha a culinária italiana , comandada com esmero pelo Chef Bruno.
        
        p Com ótimos petiscos , chocolates  e  uma equilibrada carta de vinhos e cervejas gourmet o Cantucci é um local para se conhecer e voltar sempre.
        
        p Só ou com os amigos , curta o Cantucci!!!

        
        p Chamadas na página de abertura :
        
        p Faça o evento de sua empresa conosco!!! Local para 70 pessoas sentadas.
        
        p Todas as terças, temos um projeto com excelentes músicos de Brasília.
                
        
    #col2
      #enquete
        - @enquete.each do |enq|
          h4 = enq.pergunta
          br
          = form_for :enqueteForm, :url => update_path do 
            input#Opt1 type="radio" name="opcao_usuario" value=enq.op1
            label for="Opt1" =enq.op1 
            br
            input#Opt2 type="radio" name="opcao_usuario" value=enq.op2
            label for="Opt2" =enq.op2
            br
            input#Opt3 type="radio" name="opcao_usuario" value=enq.op3    
            label for="Opt3"  =enq.op3
            br
            input type="submit" value="Responder" class="botao"


      a#face href="http://pt-br.facebook.com/pages/Cantucci-Caffè%C3%A8/121144747980778" Facebook

app/views/enquetes/iago.html.slim
- @enquete.each do |enq|

  p = enq.pergunta
  
  = form_for :enqueteForm, :url => update_path do 

    input type="radio" name="opcao_usuario" value=enq.op1 =enq.op1 
    br
    input type="radio" name="opcao_usuario" value=enq.op2 =enq.op2    
    br
    input type="radio" name="opcao_usuario" value=enq.op3 =enq.op3    
    br
    input type="submit" value="Answer"

app/views/enquetes/resultado.html.slim
.ladrilhoPrincipalHome
  img#fotoHome src="/images/foto-home.jpg"

  #divindex
    #cont 
      #QuemSomos
        h2 Quem Somos
        p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta, tellus sed faucibus venenatis, turpis mi bibendum risus, ac molestie nibh tellus nec nibh. Praesent felis lorem, porttitor nec sodales quis, adipiscing eget purus. Etiam dui orci, molestie eu dictum vel, faucibus eget nulla. Donec cursus quam vel augue venenatis euismod. Nunc nulla turpis, bibendum et viverra eget, dignissim in ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin in purus quis justo pharetra aliquam. Nunc porta fermentum quam non pharetra. Nunc viverra malesuada ornare. Donec cursus quam vel augue venenatis euismod. Nunc nulla turpis, bibendum et viverra eget, dignissim in ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin in purus quis justo pharetra aliquam. Nunc porta fermentum quam non pharetra. Nunc viverra malesuada ornare.   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta, tellus sed faucibus venenatis, turpis mi bibendum risus, ac molestie nibh tellus nec nibh. Praesent felis lorem. 
  
    #col2
      #enquete
        h1 Resultado
        -@enquete.each do |enq|
          h3 = enq.op1
          = @porc1
          br
          h3 = enq.op2
          = @porc2  
          br
          h3 = enq.op3
          = @porc3
          br
        = link_to 'Voltar', root_path


      a#face href="#" Facebook

app/views/eventos/index.html.slim
.ladrilhoPrincipal
  #Agenda
  	h2 Agenda

  -@eventos.each do |evento|
    .column1
      .calendario
  	      h4#mes=evento.data_e_hora.strftime("%B")
        	h4#dia=evento.data_e_hora.strftime("%d") 
      .evento
  		    h3 =evento.title
      		br
      		p =evento.description
  
    .column2
      =image_tag(evento.foto.icon.url) if evento.foto.present?
  
  
    br
    span#divisao

app/views/fotos/index.html.slim
.ladrilhoPrincipal
  #Fotos
    h2 Fotos
  .containerFotos
    -@fotos.each do |foto| 
      = image_tag(foto.picture.thumb.url) if foto.picture.present?
        

app/views/vinhos/index.html.slim
.ladrilhoPrincipal
  #Carta
    h2 Carta de Vinhos
    -@categorias.each do |categoria|
      .categoriaCardapio
        .colunaEsquerda
          h3 = categoria.title
          br
          span
          br
          -@vinhos.each do |v|
            - if v.vinho_categoria_id == categoria.id
              h4 = v.title
              br
              p = v.description.html_safe 
              br

    
  
    / - @categorias.each do |cat|
    /   .categoriaCardapio
    /      h3 = cat.title
    /      br
    /      span
    /      br
    /   - @vinhos.each do |v| 
    /     - if v.cardapio_categoria_id == cat.id
    /       h4 = v.title
    /       br
    /       p = v.description.html_safe
    /       br

		
		
		
		
	